version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword  # Change this password for production
      POSTGRES_DB: payment_processor
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
